{{- if include "ngas.createCredentials" . }}
# Created only when vngcloud.credentials.clientId/clientSecret are set in values (for testing). The usual way
# is a Secret created out of band and referenced by vngcloud.credentials.existingSecret.
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ngas.credentialsSecret" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "ngas.labels" . | nindent 4 }}
type: Opaque
stringData:
  clientId: {{ .Values.vngcloud.credentials.clientId | quote }}
  clientSecret: {{ .Values.vngcloud.credentials.clientSecret | quote }}
{{- end }}
